openapi: 3.1.0
info:
  title: Business Nexus
  description: API endpoints for managing business nexus data.
  version: "1.0.9"

servers:
  - url: https://api.ecommerceapi.uk/v1
    description: Production API server

paths:
  /nexuses:
    get:
      summary: List business nexus items
      description: "Retrieves a list of business nexus items with pagination."
      operationId: listBusinessNexus
      security:
        - BasicAuth: []
      parameters:
        - name: count
          in: query
          description: "Number of records to retrieve (default: 50, max: 100)."
          required: false
          schema:
            type: integer
            default: 50
            maximum: 100
        - name: offset
          in: query
          description: "Number of records to skip."
          required: false
          schema:
            type: integer
            default: 0
        - name: fields
          in: query
          description: "Comma-separated list of fields to include in the response."
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "A list of business nexus items."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BusinessNexus"
        "400":
          description: "Invalid request parameters."
        "401":
          description: "Unauthorized. Invalid or missing API key."
        "500":
          description: "Server error."

    post:
      summary: Create a new business nexus item
      description: "Creates a new business nexus item."
      operationId: createBusinessNexus
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BusinessNexusCreate"
      responses:
        "201":
          description: "Business nexus item created successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BusinessNexus"
        "400":
          description: "Invalid request data."
        "401":
          description: "Unauthorized. Invalid or missing API key."
        "500":
          description: "Server error."

  /nexuses/{id}:
    put:
      summary: Update a business nexus item
      description: "Updates an existing business nexus item by ID. The state and type cannot be changed."
      operationId: updateBusinessNexus
      security:
        - BasicAuth: []
      parameters:
        - name: id
          in: path
          description: "The unique identifier of the business nexus item."
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BusinessNexusUpdate"
      responses:
        "200":
          description: "Business nexus item updated successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BusinessNexus"
        "400":
          description: "Invalid request data."
        "401":
          description: "Unauthorized. Invalid or missing API key."
        "404":
          description: "Business nexus item not found."
        "500":
          description: "Server error."

    delete:
      summary: Delete a business nexus item
      description: "Deletes an existing business nexus item by ID."
      operationId: deleteBusinessNexus
      security:
        - BasicAuth: []
      parameters:
        - name: id
          in: path
          description: "The unique identifier of the business nexus item."
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: "Business nexus item deleted successfully."
        "400":
          description: "Invalid request parameters."
        "401":
          description: "Unauthorized. Invalid or missing API key."
        "404":
          description: "Business nexus item not found."
        "500":
          description: "Server error."

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    BusinessNexus:
      type: object
      properties:
        id:
          type: integer
          description: "Unique identifier for the business nexus item."
        countryId:
          type: integer
          description: "Identifier for the country."
        stateId:
          type: integer
          description: "Identifier for the state."
        type:
          type: string
          description: "Type of nexus ('physical' or 'economic')."
        name:
          type: string
          description: "The name of the nexus."
        addressLine1:
          type: string
          description: "Primary address line."
        addressLine2:
          type: string
          description: "Secondary address line."
        city:
          type: string
          description: "City of the nexus."
        postcode:
          type: string
          description: "Postcode of the nexus."
        salesTaxId:
          type: string
          description: "Sales tax identification number."

    BusinessNexusCreate:
      type: object
      required:
        - countryId
        - stateId
        - type
        - name
        - addressLine1
        - city
        - postcode
      properties:
        countryId:
          type: integer
          description: "Identifier for the country."
        stateId:
          type: integer
          description: "Identifier for the state."
        type:
          type: string
          description: "Type of nexus ('physical' or 'economic')."
        name:
          type: string
          description: "The name of the nexus."
        addressLine1:
          type: string
          description: "Primary address line."
        addressLine2:
          type: string
          description: "Secondary address line."
        city:
          type: string
          description: "City of the nexus."
        postcode:
          type: string
          description: "Postcode of the nexus."
        salesTaxId:
          type: string
          description: "Sales tax identification number."

    BusinessNexusUpdate:
      type: object
      properties:
        name:
          type: string
          description: "The name of the nexus."
        addressLine1:
          type: string
          description: "Primary address line."
        addressLine2:
          type: string
          description: "Secondary address line."
        city:
          type: string
          description: "City of the nexus."
        postcode:
          type: string
          description: "Postcode of the nexus."
        salesTaxId:
          type: string
          description: "Sales tax identification number."
