openapi: 3.1.0
info:
  title: Payment Methods
  description: API endpoint for retrieving external payment methods.
  version: "1.0.1"

servers:
  - url: https://api.ecommerceapi.uk/v1
    description: Production API server

paths:
  /payment-methods:
    get:
      summary: List external payment methods
      description: "Retrieves a list of external payment methods."
      operationId: listPaymentMethods
      security:
        - BasicAuth: []
      parameters:
        - name: fields
          in: query
          description: "Comma-separated list of properties to include in the response. Available values: 'id', 'name'."
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "A list of external payment methods."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaymentMethod"
        "400":
          description: "Invalid request parameters."
        "401":
          description: "Unauthorized. Invalid or missing API key."
        "500":
          description: "Server error."

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    PaymentMethod:
      type: object
      properties:
        id:
          type: integer
          description: "The ID of the payment method."
        name:
          type: string
          description: "The name of the payment method."