openapi: 3.1.0
info:
  title: Refunds
  description: API endpoint for viewing and creating refunds attached to orders. Refunds created for orders never create a refund for the payment transaction.
  version: "1.0.1"

servers:
  - url: https://api.ecommerceapi.uk/v1
    description: Production API server

paths:
  /orders/{order_id}/refunds:
    post:
      summary: Create a refund for an order
      description: "Creates a new refund for a specific order. Refunds created through the API never create a refund for the payment transaction."
      operationId: createRefund
      security:
        - BasicAuth: []
      parameters:
        - name: order_id
          in: path
          description: "ID of the order which the refund will be assigned to."
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefundCreate"
      responses:
        "201":
          description: "Refund created successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Refund"
        "400":
          description: "Invalid request parameters."
        "401":
          description: "Unauthorized. Invalid or missing API key."
        "404":
          description: "Order not found."
        "500":
          description: "Server error."

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    Refund:
      type: object
      properties:
        amount:
          type: number
          description: "The gross amount of the refund."
        comment:
          type: string
          description: "The reason for the refund."

    RefundCreate:
      type: object
      required:
        - amount
        - comment
      properties:
        amount:
          type: number
          description: "The gross amount of the refund."
        comment:
          type: string
          description: "The reason for the refund."
