openapi: 3.1.0
info:
  title: Stock
  description: API endpoints for retrieving and updating stock quantities.
  version: "1.2.0"

servers:
  - url: https://api.ecommerceapi.uk/v1
    description: Production API server

paths:
  /stock:
    get:
      summary: Retrieve stock quantity
      description: "Returns the stock quantity for a specified SKU code."
      operationId: getStock
      security:
        - BasicAuth: []
      parameters:
        - name: sku
          in: query
          description: "The SKU code for the product or product variation."
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Stock quantity retrieved successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Stock"
        "400":
          description: "Invalid request parameters."
        "401":
          description: "Unauthorized. Invalid or missing API key."
        "500":
          description: "Server error."

    post:
      summary: Update stock quantity
      description: "Updates the stock quantity for a specified SKU code."
      operationId: updateStock
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StockUpdate"
      responses:
        "200":
          description: "Stock updated successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StockUpdateResponse"
        "400":
          description: "Invalid request data."
        "401":
          description: "Unauthorized. Invalid or missing API key."
        "500":
          description: "Server error."
  /stock/return:
    post:
      summary: Return stock for cancelled orders
      description: "Returns stock to inventory for order products when an order is cancelled."
      operationId: returnStock
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StockReturnRequest"
      responses:
        "200":
          description: "Stock returned successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StockReturnResponse"
        "400":
          description: "Invalid request data."
        "401":
          description: "Unauthorized. Invalid or missing API key."
        "500":
          description: "Operation failed."
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    Stock:
      type: object
      properties:
        sku:
          type: string
          description: "The SKU code for the product or product variation."
        quantity:
          type: integer
          description: "The current stock quantity for the SKU code."

    StockUpdate:
      type: object
      properties:
        sku:
          type: string
          description: "The SKU code for the product or product variation. Required when using 'quantity' alone. Should not be used with 'items'."
        quantity:
          type: integer
          description: "The quantity of stock for the SKU code. Required when using 'sku' alone. Should not be used with 'items'."
        items:
          type: array
          description: "Array of stock items to update. Should not be used with 'sku' or 'quantity'. Maximum of 15 items allowed."
          maxItems: 15
          items:
            type: object
            properties:
              sku:
                type: string
                description: "The SKU code for the product or product variation."
              quantity:
                type: integer
                description: "The quantity of stock for the SKU code."

    StockUpdateResponse:
      type: object
      properties:
        sku:
          type: string
          description: "The SKU code for the product or product variation. Only present when 'sku' and 'quantity' were used in the request."
        quantity:
          type: integer
          description: "The updated stock quantity. Only present when 'sku' and 'quantity' were used in the request."
        updated:
          type: integer
          description: "The count of items updated. Only present when 'items' were provided in the request."
          
    StockReturnRequest:
      type: object
      required:
        - orderProductItemId
      properties:
        orderProductItemId:
          type: integer
          description: "The unique ID of the order product item to return stock for."

    StockReturnResponse:
      type: object
      properties:
        orderProductItemId:
          type: integer
          description: "The ID of the order product item that had stock returned."
        sku:
          type: string
          description: "The SKU code for the product or variation linked to the order product item."
        quantityReturned:
          type: integer
          description: "The quantity of stock returned to inventory."
        message:
          type: string
          description: "Confirmation or error message."
