openapi: 3.1.0
info:
  title: Trade Groups
  description: API endpoints for managing trade pricing bands.
  version: "1.0.2"

servers:
  - url: https://api.ecommerceapi.uk/v1
    description: Production API server

paths:
  /trade-groups:
    get:
      summary: List trade pricing bands
      description: "Retrieves a list of trade pricing bands. By default, the first 50 are returned."
      operationId: listTradeGroups
      security:
        - BasicAuth: []
      parameters:
        - name: count
          in: query
          description: "Number of records to retrieve (default: 50, max: 100)."
          required: false
          schema:
            type: integer
            default: 50
            maximum: 100
        - name: offset
          in: query
          description: "Number of records to skip."
          required: false
          schema:
            type: integer
            default: 0
        - name: fields
          in: query
          description: "Comma-separated list of fields to include in the response."
          required: false
          schema:
            type: string
        - name: embed
          in: query
          description: "Comma-separated list of related resources to embed. Available: 'products'."
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "A list of trade pricing bands."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TradeGroup"

    post:
      summary: Create a trade pricing band
      description: "Creates a new trade pricing band."
      operationId: createTradeGroup
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TradeGroupCreate"
      responses:
        "201":
          description: "Trade pricing band created successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TradeGroup"

  /trade-groups/{id}:
    get:
      summary: Get a specific trade pricing band
      description: "Retrieves a single trade pricing band by ID."
      operationId: getTradeGroupById
      security:
        - BasicAuth: []
      parameters:
        - name: id
          in: path
          description: "The unique identifier of the trade pricing band."
          required: true
          schema:
            type: integer
        - name: fields
          in: query
          description: "Comma-separated list of fields to include in the response."
          required: false
          schema:
            type: string
      responses:
        "200":
          description: "Trade pricing band details."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TradeGroup"

    put:
      summary: Update a trade pricing band
      description: "Updates an existing trade pricing band. All product prices must be specified (including those already configured) when updating a trade pricing band. If not specified, product prices already configured will be removed."
      operationId: updateTradeGroup
      security:
        - BasicAuth: []
      parameters:
        - name: id
          in: path
          description: "The unique identifier of the trade pricing band."
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TradeGroupUpdate"
      responses:
        "200":
          description: "Trade pricing band updated successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TradeGroup"

    delete:
      summary: Delete a trade pricing band
      description: "Deletes an existing trade pricing band."
      operationId: deleteTradeGroup
      security:
        - BasicAuth: []
      parameters:
        - name: id
          in: path
          description: "The unique identifier of the trade pricing band."
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: "Trade pricing band deleted successfully."

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    TradeGroup:
      type: object
      properties:
        id:
          type: integer
          description: "Unique identifier for the trade pricing band."
        title:
          type: string
          description: "The name of the trade pricing band."
        products:
          type: array
          description: "The products and their pricing in the pricing band."
          items:
            $ref: "#/components/schemas/ProductPrice"
          required: true

    TradeGroupCreate:
      type: object
      required:
        - title
        - products
      properties:
        title:
          type: string
          description: "The name of the trade pricing band."
        products:
          type: array
          description: "The products and their pricing in the pricing band."
          items:
            $ref: "#/components/schemas/ProductPrice"
          required: true

    TradeGroupUpdate:
      type: object
      required:
        - products
      properties:
        title:
          type: string
          description: "The updated name of the trade pricing band."
        products:
          type: array
          description: "Updated list of products and their pricing."
          items:
            $ref: "#/components/schemas/ProductPrice"
          required: true

    ProductPrice:
      type: object
      required:
        - id
        - sku
        - price
      properties:
        id:
          type: integer
          description: "The unique ID of the product."
        sku:
          type: string
          description: "SKU of the product or variation."
        price:
          type: number
          format: float
          description: "The price of the product within the pricing band."